services:
  postgres:
    image: postgres:17
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dl.com
      PGADMIN_DEFAULT_PASSWORD: devpass
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
    - ./pgadmin_data:/var/lib/pgadmin

